name: Build-Test

on:
  push:
    branches:
      - dev
    paths-ignore: 
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
      - '**.http'

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run Gradle build
        run: |
          ./gradlew clean build
