name: Build-Test

on:
  pull_request:
    branches:
      - main

jobs:
  maven-local-test:
    name: Maven local test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: publishKotlinOSSRHPublicationToMavenLocal
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}