name: Build-Test

on:
  pull_request:
    types: [opened, synchronized, reopened, edited]
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    strategy:
      matrix:
        mongodb-version: ['4.4', '5.0', '6.0']
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
  assembly-tests:
    name: Assemble test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Setup and execute Gradle 'assemble' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble