name: Build-Test

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
