name: Release Please

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: smartparking
  push_image_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ needs.release_please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ./Docker/Dockerfile

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Docker/Dockerfile
          tags: giuliozaccaroni/smart-parking-backend:latest,giuliozaccaroni/smart-parking-backend:${{ needs.release_please.outputs.release_version }}
